name: "policykit"
description: "Tools for working with Open Policy Agent"
author: "Gareth Rushgrove"
inputs:
  command:
    description: "Which command to run, defaults to build"
    default: build
  args:
    description: "Additional arguments to pass to policykit"
runs:
  using: "docker"
  image: "docker://garethr/policykit:latest"
  args:
  - ${{ inputs.command }}
  - ${{ inputs.args }} 
