version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
            - deps-
      - run:
          name: install dependencies
          command: |
            poetry instal
      - save_cache:
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
          key: deps-{{ checksum "poetry.lock" }}
      - run:
          name: run tests
          command: |
            poetry run pytest
